### ISSUE TITLE
The bean 'commandGateway', defined in class path resource [.../AxonAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [.../TracingAutoConfiguration.class] and overriding is disabled.

### ISSUE THREAD

**Issue by guilhermeblanco** [AxonFramework/extension-tracing#79]
Running with Spring Boot v2.3.3.RELEASE, Spring v5.2.8.RELEASE
When combining axon libraries for local development:

```
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-spring-boot-starter</artifactId>
            <version>${axonframework.version}</version>
        </dependency>

        <dependency>
            <groupId>org.axonframework.extensions.tracing</groupId>
            <artifactId>axon-tracing-spring-boot-starter</artifactId>
            <version>4.3.1</version>
        </dependency>
``` 

Local development (`mvn spring-boot:run`) is unable to proceed due to error mentioned in the title.
This does not happen in any other environment aside from local dev. For the reference, I have the following configuration (and haven't configured any environment variable):

```
opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:false}
    service-name: ${spring.application.name}
    udp-sender:
      host: "${JAEGER_HOST:localhost}"
      port: "${JAEGER_PORT:6831}"
```

Ideally (and aside from this bug), this extension should be picking a configuration flag instead of looking up for the presence of `io.opentracking.Tracer` class.
